<script setup>
import { ref, onMounted, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { NewLabelOutlined, EmailOutlined } from '@vicons/material'

import AdminContact from '../common/AdminContact.vue'
import Turnstile from '../../components/Turnstile.vue'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import { getRouterPathWithLang, hashPassword } from '../../utils'

const props = defineProps({
    bindUserAddress: {
        type: Function,
        default: async () => { await api.bindUserAddress(); },
        required: true
    },
    newAddressPath: {
        type: Function,
        default: async (address_name, domain, cf_token, enableRandomSubdomain) => {
            return await api.fetch("/api/new_address", {
                method: "POST",
                body: JSON.stringify({
                    name: address_name,
                    domain: domain,
                    cf_token: cf_token,
                    enableRandomSubdomain: enableRandomSubdomain,
                }),
            });
        },
        required: true
    },
})

const message = useMessage()
const notification = useNotification()
const router = useRouter()

const {
    jwt, loading, openSettings,
    showAddressCredential, userSettings, addressPassword
} = useGlobalState()

const tabValue = ref('signin')
const credential = ref('')
const emailName = ref("")
const emailDomain = ref("")
const cfToken = ref("")
const enableRandomSubdomain = ref(false)
const loginCfToken = ref("")
const loginTurnstileRef = ref(null)
const loginMethod = ref('credential') // 'credential' or 'password'
const loginAddress = ref('')
const loginPassword = ref('')

// 根据 openSettings 初始化登录方式
const initLoginMethod = () => {
    if (openSettings.value?.enableAddressPassword) {
        loginMethod.value = 'password';
    } else {
        loginMethod.value = 'credential';
    }
}

const login = async () => {
    if (loginMethod.value === 'password') {
        // Password login
        if (!loginAddress.value || !loginPassword.value) {
            message.error(t('emailPasswordRequired'));
            return;
        }
        try {
            const res = await api.fetch('/api/address_login', {
                method: 'POST',
                body: JSON.stringify({
                    email: loginAddress.value,
                    password: await hashPassword(loginPassword.value),
                    cf_token: loginCfToken.value
                })
            });
            jwt.value = res.jwt;
            await api.getSettings();
            try {
                await props.bindUserAddress();
            } catch (error) {
                message.error(`${t('bindUserAddressError')}: ${error.message}`);
            }
            await router.push(getRouterPathWithLang("/", locale.value));
        } catch (error) {
            message.error(error.message || "error");
            loginTurnstileRef.value?.refresh?.();
        }
        return;
    }
    if (!credential.value) {
        message.error(t('credentialInput'));
        return;
    }
    try {
        await api.fetch('/open_api/credential_login', {
            method: 'POST',
            body: JSON.stringify({
                credential: credential.value,
                cf_token: loginCfToken.value
            })
        });
        jwt.value = credential.value;
        await api.getSettings();
        try {
            await props.bindUserAddress();
        } catch (error) {
            message.error(`${t('bindUserAddressError')}: ${error.message}`);
        }
        await router.push(getRouterPathWithLang("/", locale.value));
    } catch (error) {
        message.error(error.message || "error");
        loginTurnstileRef.value?.refresh?.();
    }
}

const { locale, t } = useI18n({
    messages: {
        en: {
            login: 'Login',
            loginAndBind: 'Login and Bind',
            pleaseGetNewEmail: 'Please login or click "Get New Email" button to get a new email address',
            getNewEmail: 'Create New Email',
            getNewEmailTip1: 'Please input the email you want to use. only allow: ',
            getNewEmailTip2: 'Levaing it blank will generate a random email address.',
            getNewEmailTip3: 'You can choose a domain from the dropdown list.',
            credential: 'Email Address Credential',
            ok: 'OK',
            generateName: 'Generate Fake Name',
            help: 'Help',
            credentialInput: 'Please input the Mail Address Credential',
            bindUserInfo: 'Logged in user, login without binding email or create new email address will bind to current user',
            bindUserAddressError: 'Error when bind email address to user',
            autoGeneratedName: 'Auto-generated name',
            passwordLogin: 'Password Login',
            credentialLogin: 'Credential Login',
            email: 'Email',
            password: 'Password',
            emailPasswordRequired: 'Email and password are required',
            enableRandomSubdomain: 'Use Random Subdomain',
            randomSubdomainTip: 'When enabled, the created address will use a random subdomain. Subdomain addresses are recommended for receiving only.',
        },
        zh: {
            login: '登录',
            loginAndBind: '登录并绑定',
            pleaseGetNewEmail: '请"登录"或点击 "注册新邮箱" 按钮来获取一个新的邮箱地址',
            getNewEmail: '创建新邮箱',
            getNewEmailTip1: '请输入你想要使用的邮箱地址, 只允许: ',
            getNewEmailTip2: '留空将会生成一个随机的邮箱地址。',
            getNewEmailTip3: '你可以从下拉列表中选择一个域名。',
            credential: '邮箱地址凭据',
            ok: '确定',
            generateName: '生成随机名字',
            help: '帮助',
            credentialInput: '请输入邮箱地址凭据',
            bindUserInfo: '已登录用户, 登录未绑定邮箱或创建新邮箱地址将绑定到当前用户',
            bindUserAddressError: '绑定邮箱地址到用户时错误',
            autoGeneratedName: '自动生成名称',
            passwordLogin: '密码登录',
            credentialLogin: '凭据登录',
            email: '邮箱',
            password: '密码',
            emailPasswordRequired: '邮箱和密码不能为空',
            enableRandomSubdomain: '启用随机子域名',
            randomSubdomainTip: '启用后，创建出来的地址会自动挂在随机子域名下。子域名地址更建议仅用于收件。',
        }
    }
});

const loginAndBindTag = computed(() => {
    if (userSettings.value.user_email) {
        return t('loginAndBind')
    }
    return t('login')
})

const addressRegex = computed(() => {
    try {
        if (openSettings.value.addressRegex) {
            return new RegExp(openSettings.value.addressRegex, 'g');
        }
    } catch (error) {
        console.error(error);
        message.error(`Invalid addressRegex: ${openSettings.value.addressRegex}`);
    }
    return /[^a-z0-9]/g;
});

const generateNameLoading = ref(false);
const generateName = async () => {
    try {
        generateNameLoading.value = true;
        const { faker } = await import('https://esm.sh/@faker-js/faker');
        emailName.value = faker.internet.email()
            .split('@')[0]
            .replace(/\s+/g, '.')
            .replace(/\.{2,}/g, '.')
            .replace(addressRegex.value, '')
            .toLowerCase();
        // support maxAddressLen
        if (emailName.value.length > openSettings.value.maxAddressLen) {
            emailName.value = emailName.value.slice(0, openSettings.value.maxAddressLen);
        }
    } catch (error) {
        message.error(error.message || "error");
    } finally {
        generateNameLoading.value = false;
    }
};

const newEmail = async () => {
    try {
        // If custom names are disabled, send empty name to trigger backend auto-generation
        const nameToSend = openSettings.value.disableCustomAddressName ? "" : emailName.value;
        const res = await props.newAddressPath(
            nameToSend,
            emailDomain.value,
            cfToken.value,
            enableRandomSubdomain.value
        );
        jwt.value = res["jwt"];
        addressPassword.value = res["password"] || '';
        await api.getSettings();
        await router.push(getRouterPathWithLang("/", locale.value));
        showAddressCredential.value = true;
        try {
            await props.bindUserAddress();
        } catch (error) {
            message.error(`${t('bindUserAddressError')}: ${error.message}`);
        }
    } catch (error) {
        message.error(error.message || "error");
    }
};

const addressPrefix = computed(() => {
    // if user has role, return role prefix
    if (userSettings.value?.user_role) {
        return userSettings.value.user_role.prefix || "";
    }
    // if user has no role, return default prefix
    return openSettings.value.prefix;
});

const canUseRandomSubdomain = computed(() => {
    if (!emailDomain.value) {
        return false;
    }
    return (openSettings.value.randomSubdomainDomains || []).includes(emailDomain.value);
});

watch(canUseRandomSubdomain, (enabled) => {
    // Random subdomain toggle is hidden in UI, so sync it from capability.
    enableRandomSubdomain.value = enabled;
}, { immediate: true });

const domainsOptions = computed(() => {
    // if user has role, return role domains
    if (userSettings.value.user_role) {
        const allDomains = userSettings.value.user_role.domains;
        if (!allDomains) return openSettings.value.domains;
        return openSettings.value.domains.filter((domain) => {
            return allDomains.includes(domain.value);
        });
    }
    // if user has no role, return default domains
    if (!openSettings.value.defaultDomains) {
        return openSettings.value.domains;
    }
    // if user has no role and no default domains, return all domains
    return openSettings.value.domains.filter((domain) => {
        return openSettings.value.defaultDomains.includes(domain.value);
    });
});

const showNewAddressTab = computed(() => {
    if (openSettings.value.disableAnonymousUserCreateEmail
        && !userSettings.value.user_email
    ) {
        return false;
    }
    return openSettings.value.enableUserCreateEmail;
});

onMounted(async () => {
    if (!openSettings.value.domains || openSettings.value.domains.length === 0) {
        await api.getOpenSettings(message, notification);
    }
    emailDomain.value = domainsOptions.value ? domainsOptions.value[0]?.value : "";
    initLoginMethod();
});
</script>

<template>
    <section class="auth-shell">
        <div class="hero-copy">
            <p class="eyebrow">Cloudflare Temp Email</p>
            <h2 class="hero-title">{{ t('getNewEmail') }}</h2>
            <p class="hero-desc">Create isolated inboxes in seconds, then inspect and manage messages from one clean workspace.</p>
        </div>
        <n-alert v-if="userSettings.user_email" class="bind-alert" :show-icon="false" :bordered="false" closable>
            <span>{{ t('bindUserInfo') }}</span>
        </n-alert>
        <n-tabs class="auth-tabs" v-if="openSettings.fetched" v-model:value="tabValue" size="large" type="segment" animated justify-content="space-evenly">
            <n-tab-pane name="signin" :tab="loginAndBindTag">
                <n-form class="auth-form">
                    <div v-if="loginMethod === 'password'">
                        <n-form-item-row :label="t('email')" required>
                            <n-input v-model:value="loginAddress" />
                        </n-form-item-row>
                        <n-form-item-row :label="t('password')" required>
                            <n-input v-model:value="loginPassword" type="password" show-password-on="click" />
                        </n-form-item-row>
                    </div>

                    <div v-else>
                        <n-form-item-row :label="t('credential')" required>
                            <n-input v-model:value="credential" type="textarea" :autosize="{ minRows: 3 }" />
                        </n-form-item-row>
                    </div>

                    <Turnstile ref="loginTurnstileRef" v-if="openSettings.enableGlobalTurnstileCheck"
                        v-model:value="loginCfToken" />

                    <div class="switch-login-button">
                        <n-button v-if="openSettings?.enableAddressPassword"
                            @click="loginMethod === 'password' ? loginMethod = 'credential' : loginMethod = 'password'"
                            type="info" quaternary size="tiny">
                            {{ loginMethod === 'password' ? t('credentialLogin') : t('passwordLogin') }}
                        </n-button>
                    </div>

                    <n-button class="primary-action" @click="login" :loading="loading" type="primary" block strong>
                        <template #icon>
                            <n-icon :component="EmailOutlined" />
                        </template>
                        {{ loginAndBindTag }}
                    </n-button>
                    <n-button class="secondary-action" v-if="showNewAddressTab" @click="tabValue = 'register'" block secondary strong>
                        <template #icon>
                            <n-icon :component="NewLabelOutlined" />
                        </template>
                        {{ t('getNewEmail') }}
                    </n-button>
                </n-form>
            </n-tab-pane>
            <n-tab-pane v-if="showNewAddressTab" name="register" :tab="t('getNewEmail')">
                <n-spin :show="generateNameLoading">
                    <n-form class="auth-form">
                        <div class="tip-block">
                            <p v-if="!openSettings.disableCustomAddressName">{{ t("getNewEmailTip1") +
                                addressRegex.source }}</p>
                            <p v-if="!openSettings.disableCustomAddressName">{{ t("getNewEmailTip2") }}</p>
                            <p>{{ t("getNewEmailTip3") }}</p>
                        </div>
                        <n-button class="secondary-action" v-if="!openSettings.disableCustomAddressName" @click="generateName">
                            {{ t('generateName') }}
                        </n-button>
                        <n-input-group>
                            <n-input-group-label v-if="addressPrefix">
                                {{ addressPrefix }}
                            </n-input-group-label>
                            <n-input v-if="!openSettings.disableCustomAddressName" v-model:value="emailName" show-count
                                :minlength="openSettings.minAddressLen" :maxlength="openSettings.maxAddressLen" />
                            <n-input v-else :value="t('autoGeneratedName')" disabled />
                            <n-input-group-label>@</n-input-group-label>
                            <n-select v-model:value="emailDomain" :consistent-menu-width="false"
                                :options="domainsOptions" />
                        </n-input-group>
                        <!-- Random subdomain forced on, checkbox hidden -->
                        <Turnstile v-model:value="cfToken" />
                        <n-button class="primary-action" type="primary" block strong @click="newEmail" :loading="loading">
                            <template #icon>
                                <n-icon :component="NewLabelOutlined" />
                            </template>
                            {{ t('getNewEmail') }}
                        </n-button>
                    </n-form>
                </n-spin>
            </n-tab-pane>
            <n-tab-pane name="help" :tab="t('help')">
                <n-alert class="help-alert" :show-icon="false" :bordered="false">
                    <span>{{ t('pleaseGetNewEmail') }}</span>
                </n-alert>
                <AdminContact />
            </n-tab-pane>
        </n-tabs>
    </section>
</template>


<style scoped>
.auth-shell {
    max-width: 860px;
    margin: 8px auto 0;
    padding: 8px 6px;
    text-align: left;
    animation: rise-in 300ms cubic-bezier(0.22, 1, 0.36, 1);
}

.hero-copy {
    margin: 8px 4px 14px;
}

.eyebrow {
    margin: 0 0 6px;
    color: color-mix(in srgb, var(--text-muted) 72%, #8fb3ff);
    font-size: 0.78rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.08em;
}

.hero-title {
    margin: 0;
    font-size: clamp(1.36rem, 2.2vw, 1.94rem);
    line-height: 1.25;
    color: var(--text-strong);
    letter-spacing: -0.01em;
    text-wrap: balance;
}

.hero-desc {
    margin: 8px 0 0;
    color: var(--text-muted);
    max-width: 62ch;
    line-height: 1.65;
    text-wrap: pretty;
}

.bind-alert {
    margin: 6px 0 12px;
    border-radius: 14px;
    background: color-mix(in srgb, var(--glass-top) 62%, transparent);
    border: 1px solid var(--glass-border);
    backdrop-filter: blur(14px) saturate(160%);
}

.auth-tabs {
    border: 1px solid var(--glass-border);
    border-radius: 20px;
    background:
        linear-gradient(140deg, var(--glass-top) 0%, var(--glass-bottom) 100%);
    backdrop-filter: blur(24px) saturate(180%);
    box-shadow: var(--glass-shadow);
    position: relative;
    overflow: hidden;
}

.auth-tabs::before {
    content: "";
    position: absolute;
    inset: 0;
    pointer-events: none;
    border-radius: inherit;
    background:
        radial-gradient(100% 58% at 6% 0%, rgba(255, 255, 255, 0.52), transparent 56%),
        linear-gradient(180deg, rgba(255, 255, 255, 0.22) 0%, transparent 34%);
}

.auth-tabs :deep(.n-tabs-nav) {
    border-radius: 14px;
    background: color-mix(in srgb, var(--glass-top) 58%, transparent);
    border: 1px solid color-mix(in srgb, var(--glass-border) 78%, transparent);
    backdrop-filter: blur(14px);
}

.auth-tabs :deep(.n-tabs-tab) {
    min-height: 42px;
}

.auth-tabs :deep(.n-base-selection-label) {
    color: var(--text-strong);
}

.auth-form {
    display: flex;
    flex-direction: column;
    gap: 9px;
    padding-top: 8px;
}

.auth-form :deep(.n-form-item-label__text) {
    color: var(--text-muted);
    font-weight: 600;
}

.auth-form :deep(.n-input),
.auth-form :deep(.n-base-selection) {
    border-radius: 13px;
    backdrop-filter: blur(8px);
    transition: transform 160ms cubic-bezier(0.22, 1, 0.36, 1), border-color 160ms ease, box-shadow 160ms ease;
}

.auth-form :deep(.n-input:focus-within),
.auth-form :deep(.n-base-selection:focus-within) {
    transform: translateY(-1px);
    box-shadow: 0 10px 24px -18px rgba(72, 112, 201, 0.85);
}

.tip-block {
    margin-bottom: 4px;
    padding: 10px 12px;
    border-radius: 12px;
    border: 1px solid color-mix(in srgb, var(--glass-border) 70%, transparent);
    background: color-mix(in srgb, var(--glass-top) 52%, transparent);
}

.tip-block p {
    margin: 0 0 7px;
    color: var(--text-muted);
    line-height: 1.5;
}

.switch-login-button {
    display: flex;
    justify-content: center;
    margin: 2px 0;
}

.primary-action,
.secondary-action {
    margin-top: 5px;
    min-height: 44px;
    transition: transform 180ms cubic-bezier(0.22, 1, 0.36, 1), box-shadow 180ms ease;
}

.primary-action:hover,
.secondary-action:hover {
    transform: translateY(-1px);
}

.help-alert {
    border-radius: 14px;
    border: 1px solid color-mix(in srgb, var(--glass-border) 70%, transparent);
    background: color-mix(in srgb, var(--glass-top) 54%, transparent);
}

@keyframes rise-in {
    from {
        opacity: 0;
        transform: translate3d(0, 10px, 0);
    }
    to {
        opacity: 1;
        transform: translate3d(0, 0, 0);
    }
}

@media (max-width: 768px) {
    .auth-shell {
        margin-top: 4px;
        padding: 2px;
    }

    .hero-copy {
        margin: 4px 2px 10px;
    }

    .hero-desc {
        font-size: 0.92rem;
        line-height: 1.55;
    }

    .auth-tabs {
        border-radius: 16px;
    }

    .tip-block {
        padding: 8px 10px;
    }
}

@media (prefers-reduced-motion: reduce) {
    .auth-shell {
        animation: none;
    }

    .auth-form :deep(.n-input),
    .auth-form :deep(.n-base-selection),
    .primary-action,
    .secondary-action {
        transition: none;
    }

    .auth-form :deep(.n-input:focus-within),
    .auth-form :deep(.n-base-selection:focus-within),
    .primary-action:hover,
    .secondary-action:hover {
        transform: none;
        box-shadow: none;
    }

    .auth-tabs {
        backdrop-filter: none;
    }
}
</style>
